Nocturne intro tutorials
facebookresearch/nocturne pull request #65
Opened 2023-04-22 16:46 UTC by daphnecor

**Description**
This pull request adds two introduction tutorials. These tutorials are part of a series of four and are intended to help users get started with Nocturne.

- [x] `01_data_structure.ipynb` provides an introduction to the supported data structure used in Nocturne. It walks through a traffic scenario that is constructed from the Waymo dataset.
- [x]  `02_nocturne_concepts.ipynb` covers the basic concepts in the Nocturne simulator. 
- [ ] `03_imitation_learning.ipynb` is based on the scripts in the `imitation_learning` folder and walks through a basic imitation learning setup in Nocturne. 
- [ ] `04_reinforcement_learning` walks through a basic RL environment setup in Nocturne.

Thank you for considering this pull request. I hope that these tutorials will be useful to the Nocturne community and look forward to your feedback!

2023-04-22 17:08 UTC, eugenevinitsky commented
Hey Daphne, super excited about this! As discussed, could you convert these into jupytext notebooks? This makes it a lot easier to review and commit since it's plain markdown

2023-04-22 17:35 UTC, daphnecor commented
Thank you @eugenevinitsky! I added Markdown versions of the notebook in [commit 
0a94e49](https://github.com/facebookresearch/nocturne/pull/65/commits/0a94e493f380f6bd86ff6109a62857e3d8ccaf66).

Let me know if you would like me to remove the original `.ipynb` files.

2023-04-26 00:12 UTC, eugenevinitsky commented
Hey Daphne, yes removing the notebooks would be great so that the commit is clean!

2023-04-26 00:13 UTC, eugenevinitsky commented on docs/tutorials/01_data_structure.md
> +This is a list of different road objects in the traffic scene. For each road object, we have information about its position, velocity, size, in which direction its heading, whether its a valid object
nit: should be `in which direction it's heading, whether it's a valid object` as these are not possessives but contractions of `it is`.

2023-04-26 00:15 UTC, eugenevinitsky commented on docs/tutorials/02_nocturne_concepts.md
> +- The step method advances the simulation with a desired step size. By default, the dynamics of vehicles are driven by a kinematic bicycle model. If a vehicle is set to expert-controlled mode, its po
nit `recorded from a human driver` rather than `created by a human expert`

2023-04-26 00:16 UTC, eugenevinitsky commented on docs/tutorials/02_nocturne_concepts.md
> +The shape of the visible state is a function of the maximum number of visible objects defined at initialization (traffic lights, stop signs, road objects, and road points) and whether we add padding.
I'd add an explanation of what the padding does. For example, if we have less than max_visible_objects then...

2023-04-26 00:17 UTC, eugenevinitsky requested changes
Looks great! Thank you for doing this. I've added a tiny number of nitpicks and would appreciate if you can add jupytext to the requirements as well as brief instructions on how to use it to the README.md
Otherwise, looks good and will be approved.

2023-05-02 16:25 UTC, daphnecor commented
Alright! Integrated your feedback for tutorials 1 + 2, and just added number 3 on imitation learning.

2024-06-18 22:56 UTC, merged